APP_MONGODB_USERNAME=""
APP_MONGODB_PASSWORD=""
APP_SMTP_HOST=""
APP_SMTP_PORT=""
APP_SMTP_SSL=""
APP_SMTP_AUTH=""
APP_SMTP_USERNAME=""
APP_SMTP_PASSWORD=""

export APP_MONGODB_USERNAME \
APP_MONGODB_PASSWORD \
APP_SMTP_HOST \
APP_SMTP_PORT \
APP_SMTP_SSL \
APP_SMTP_AUTH \
APP_SMTP_USERNAME \
APP_SMTP_PASSWORD

export PATH="${OPENSHIFT_DATA_DIR}vertx/bin:${OPENSHIFT_DATA_DIR}Java7/bin:$PATH"
export JAVA_HOME="${OPENSHIFT_DATA_DIR}Java7"